import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../viewmodel/settings_viewmodel.dart';

class AppLanguageHelper {
  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'drgodly': 'DRGODLY',
      'hi': 'HI',
      'patient': 'PATIENT',
      'steps': 'STEPS',
      'calories': 'CALORIES',
      'active_time': 'ACTIVE TIME',
      'sleep': 'SLEEP',
      'general_app_config': 'GENERAL APP CONFIG',
      'app_language': 'App Language',
      'start_week_on': 'Start week on',
      'select_language': 'SELECT LANGUAGE',
      'start_week_title': 'START WEEK ON',
      'specialists_directory': 'SPECIALISTS DIRECTORY',
      'select_date_time': 'SELECT DATE & TIME',
      'review_booking': 'REVIEW BOOKING',
      'booking_confirmed': 'BOOKING CONFIRMED',
      'meds_vitals_reminders': 'MEDS & VITALS REMINDERS',
      'new_reminder': 'NEW REMINDER',
      'edit_reminder': 'EDIT REMINDER',
      'patient_profile': 'PATIENT PROFILE',
      'save_profile': 'SAVE PROFILE',
      'connected_devices': 'Connected Devices',
    },
    'Français': {
      'drgodly': 'DRGODLY',
      'hi': 'BONJOUR',
      'patient': 'PATIENT',
      'steps': 'PAS',
      'calories': 'CALORIES',
      'active_time': 'TEMPS ACTIF',
      'sleep': 'SOMMEIL',
      'general_app_config': 'CONFIGURATION GENERALE',
      'app_language': 'Langue de l\'app',
      'start_week_on': 'Début de semaine',
      'select_language': 'CHOISIR LA LANGUE',
      'start_week_title': 'DEBUT DE SEMAINE',
      'specialists_directory': 'SPECIALISTES',
      'select_date_time': 'DATE & HEURE',
      'review_booking': 'REVOIR LA RESERVATION',
      'booking_confirmed': 'RESERVATION CONFIRMEE',
      'meds_vitals_reminders': 'RAPPELS MEDS & VITALS',
      'new_reminder': 'NOUVEAU RAPPEL',
      'edit_reminder': 'MODIFIER RAPPEL',
      'patient_profile': 'PROFIL DU PATIENT',
      'save_profile': 'SAUVEGARDER LE PROFIL',
      'connected_devices': 'Appareils Connectés',
    },
    'Italiano': {
      'drgodly': 'DRGODLY',
      'hi': 'CIAO',
      'patient': 'PAZIENTE',
      'steps': 'PASSI',
      'calories': 'CALORIE',
      'active_time': 'TEMPO ATTIVO',
      'sleep': 'SONNO',
      'general_app_config': 'CONFIGURAZIONE GENERALE',
      'app_language': 'Lingua dell\'app',
      'start_week_on': 'Inizio settimana',
      'select_language': 'SELEZIONA LINGUA',
      'start_week_title': 'INIZIO SETTIMANA',
      'specialists_directory': 'RUBRICA SPECIALISTI',
      'select_date_time': 'SELEZIONA DATA E ORA',
      'review_booking': 'RIEPILOGO PRENOTAZIONE',
      'booking_confirmed': 'PRENOTAZIONE CONFERMATA',
      'meds_vitals_reminders': 'PROMEMORIA MEDICI',
      'new_reminder': 'NUOVO PROMEMORIA',
      'edit_reminder': 'MODIFICA PROMEMORIA',
      'patient_profile': 'PROFILO PAZIENTE',
      'save_profile': 'SALVA PROFILO',
      'connected_devices': 'Dispositivi Connessi',
    },
    'Deutsch': {
      'drgodly': 'DRGODLY',
      'hi': 'HALLO',
      'patient': 'PATIENT',
      'steps': 'SCHRITTE',
      'calories': 'KALORIEN',
      'active_time': 'AKTIVE ZEIT',
      'sleep': 'SCHLAF',
      'general_app_config': 'ALLGEMEINE EINSTELLUNGEN',
      'app_language': 'App-Sprache',
      'start_week_on': 'Wochenstart am',
      'select_language': 'SPRACHE WÄHLEN',
      'start_week_title': 'WOCHENSTART AM',
      'specialists_directory': 'SPEZIALISTEN-VERZEICHNIS',
      'select_date_time': 'DATUM & UHRZEIT WÄHLEN',
      'review_booking': 'BUCHUNG ÜBERPRÜFEN',
      'booking_confirmed': 'BUCHUNG BESTÄTIGT',
      'meds_vitals_reminders': 'MEDIKAMENTE & VITALE REMINDER',
      'new_reminder': 'NEUER REMINDER',
      'edit_reminder': 'REMINDER BEARBEITEN',
      'patient_profile': 'PATIENTENPROFIL',
      'save_profile': 'PROFIL SPEICHERN',
      'connected_devices': 'Verbundene Geräte',
    },
    'Español': {
      'drgodly': 'DRGODLY',
      'hi': 'HOLA',
      'patient': 'PACIENTE',
      'steps': 'PASOS',
      'calories': 'CALORÍAS',
      'active_time': 'TIEMPO ACTIVO',
      'sleep': 'SUEÑO',
      'general_app_config': 'CONFIGURACIÓN GENERAL',
      'app_language': 'Idioma de la App',
      'start_week_on': 'Iniciar semana en',
      'select_language': 'SELECCIONAR IDIOMA',
      'start_week_title': 'INICIAR SEMANA EN',
      'specialists_directory': 'DIRECTORIO DE ESPECIALISTAS',
      'select_date_time': 'SELECCIONAR FECHA Y HORA',
      'review_booking': 'REVISAR RESERVA',
      'booking_confirmed': 'RESERVA CONFIRMADA',
      'meds_vitals_reminders': 'RECORDATORIOS DE SALUD',
      'new_reminder': 'NUEVO RECORDATORIO',
      'edit_reminder': 'EDITAR RECORDATORIO',
      'patient_profile': 'PERFIL DEL PACIENTE',
      'save_profile': 'GUARDAR PERFIL',
      'connected_devices': 'Dispositivos Conectados',
    },
    'Русский': {
      'drgodly': 'DRGODLY',
      'hi': 'ПРИВЕТ',
      'patient': 'ПАЦИЕНТ',
      'steps': 'ШАГИ',
      'calories': 'КАЛОРИИ',
      'active_time': 'АКТИВНОСТЬ',
      'sleep': 'СОН',
      'general_app_config': 'ОБЩИЕ НАСТРОЙКИ',
      'app_language': 'Язык приложения',
      'start_week_on': 'Неделя начинается с',
      'select_language': 'ВЫБРАТЬ ЯЗЫК',
      'start_week_title': 'НЕДЕЛЯ НАЧИНАЕТСЯ С',
      'specialists_directory': 'СПИСОК СПЕЦИАЛИСТОВ',
      'select_date_time': 'ВЫБРАТЬ ДАТУ И ВРЕМЯ',
      'review_booking': 'ПОДТВЕРЖДЕНИЕ ЗАПИСИ',
      'booking_confirmed': 'ЗАПИСЬ ПОДТВЕРЖДЕНА',
      'meds_vitals_reminders': 'НАПОМИНАНИЯ',
      'new_reminder': 'НОВОЕ НАПОМИНАНИЕ',
      'edit_reminder': 'ИЗМЕНИТЬ НАПОМИНАНИЕ',
      'patient_profile': 'ПРОФИЛЬ ПАЦИЕНТА',
      'save_profile': 'СОХРАНИТЬ ПРОФИЛЬ',
      'connected_devices': 'Подключенные устройства',
    },
    'Português': {
      'drgodly': 'DRGODLY',
      'hi': 'OLÁ',
      'patient': 'PACIENTE',
      'steps': 'PASSOS',
      'calories': 'CALORIAS',
      'active_time': 'TEMPO ATIVO',
      'sleep': 'SONO',
      'general_app_config': 'CONFIGURAÇÕES GERAIS',
      'app_language': 'Idioma do App',
      'start_week_on': 'Começar a semana em',
      'select_language': 'SELECIONAR IDIOMA',
      'start_week_title': 'COMEÇAR A SEMAÑA EM',
      'specialists_directory': 'DIRETÓRIO DE ESPECIALISTAS',
      'select_date_time': 'SELECIONAR DATA E HORA',
      'review_booking': 'REVISAR RESERVA',
      'booking_confirmed': 'RESERVA CONFIRMADA',
      'meds_vitals_reminders': 'LEMBRETES DE SAÚDE',
      'new_reminder': 'NOVO LEMBRETE',
      'edit_reminder': 'EDITAR LEMBRETE',
      'patient_profile': 'PERFIL DO PACIENTE',
      'save_profile': 'SALVAR PERFIL',
      'connected_devices': 'Dispositivos Conectados',
    },
    'Nederlands': {
      'drgodly': 'DRGODLY',
      'hi': 'HALLO',
      'patient': 'PATIËNT',
      'steps': 'STAPPEN',
      'calories': 'CALORIEËN',
      'active_time': 'ACTIEVE TIJD',
      'sleep': 'SLAAP',
      'general_app_config': 'ALGEMENE INSTELLINGEN',
      'app_language': 'Taal van de app',
      'start_week_on': 'Week begint op',
      'select_language': 'SELECTEER TAAL',
      'start_week_title': 'WEEK BEGINT OP',
      'specialists_directory': 'SPECIALISTEN OVERZICHT',
      'select_date_time': 'DATUM & TIJD SELECTEREN',
      'review_booking': 'BOEKING CONTROLEREN',
      'booking_confirmed': 'BOEKING BEVESTIGD',
      'meds_vitals_reminders': 'MEDICIJNEN EN METINGEN',
      'new_reminder': 'NIEUWE HERINNERING',
      'edit_reminder': 'HERINNERING BEWERKEN',
      'patient_profile': 'PATIËNTENPROFIEL',
      'save_profile': 'PROFIEL OPSLAAN',
      'connected_devices': 'Gekoppelde Apparaten',
    },
    'Polski': {
      'drgodly': 'DRGODLY',
      'hi': 'WITAJ',
      'patient': 'PACJENT',
      'steps': 'KROKI',
      'calories': 'KALORIE',
      'active_time': 'CZAS AKTYWNOŚCI',
      'sleep': 'SEN',
      'general_app_config': 'USTAWIENIA GŁÓWNE',
      'app_language': 'Język aplikacji',
      'start_week_on': 'Początek tygodnia',
      'select_language': 'WYBIERZ JĘZYK',
      'start_week_title': 'POCZĄTEK TYGODNIA',
      'specialists_directory': 'KATALOG SPECJALISTÓW',
      'select_date_time': 'WYBIERZ DATE I GODZINĘ',
      'review_booking': 'PODSUMOWANIE REZERWACJI',
      'booking_confirmed': 'REZERWACJA CONFIRMOWANA',
      'meds_vitals_reminders': 'PRZYPOMNIENIA O LEKACH',
      'new_reminder': 'NOWE PRZYPOMNIENIE',
      'edit_reminder': 'EDYTUJ PRZYPOMNIENIE',
      'patient_profile': 'PROFIL PACJENTA',
      'save_profile': 'ZAPISZ PROFIL',
      'connected_devices': 'Połączone Urządzenia',
    },
    '日本語': {
      'drgodly': 'DRGODLY',
      'hi': 'こんにちは',
      'patient': '患者',
      'steps': '歩数',
      'calories': '消費カロリー',
      'active_time': 'アクティブ時間',
      'sleep': '睡眠時間',
      'general_app_config': '一般設定',
      'app_language': 'アプリ言語',
      'start_week_on': '週の開始曜日',
      'select_language': '言語選択',
      'start_week_title': '週の開始曜日',
      'specialists_directory': '専門医ディレクトリ',
      'select_date_time': '日時選択',
      'review_booking': '予約内容の確認',
      'booking_confirmed': '予約確定',
      'meds_vitals_reminders': '服薬・バイタル管理',
      'new_reminder': '新しいリマインダー',
      'edit_reminder': 'リマインダー編集',
      'patient_profile': '患者プロフィール',
      'save_profile': 'プロフィール保存',
      'connected_devices': '接続済みデバイス',
    },
    '한국어': {
      'drgodly': 'DRGODLY',
      'hi': '안녕하세요',
      'patient': '환자',
      'steps': '걸음 수',
      'calories': '칼로리',
      'active_time': '활동 시간',
      'sleep': '수면',
      'general_app_config': '일반 설정',
      'app_language': '앱 언어',
      'start_week_on': '시작 요일',
      'select_language': '언어 선택',
      'start_week_title': '시작 요일',
      'specialists_directory': '전문의 디렉토리',
      'select_date_time': '날짜 및 시간 선택',
      'review_booking': '예약 검토',
      'booking_confirmed': '예약 확정',
      'meds_vitals_reminders': '복약 및 바이탈 미리 알림',
      'new_reminder': '새 알림 추가',
      'edit_reminder': '알림 편집',
      'patient_profile': '환자 프로필',
      'save_profile': '프로필 저장',
      'connected_devices': '연결된 기기',
    },
    'Türkçe': {
      'drgodly': 'DRGODLY',
      'hi': 'MERHABA',
      'patient': 'HASTA',
      'steps': 'ADIMLAR',
      'calories': 'KALORİ',
      'active_time': 'AKTİF SÜRE',
      'sleep': 'UYKU',
      'general_app_config': 'GENEL AYARLAR',
      'app_language': 'Uygulama Dili',
      'start_week_on': 'Hafta başlangıcı',
      'select_language': 'DİL SEÇİN',
      'start_week_title': 'HAFTA BAŞLANGICI',
      'specialists_directory': 'UZMAN DİZİNİ',
      'select_date_time': 'TARİH & SAAT SEÇİN',
      'review_booking': 'RANDEVU GÖZDEN GEÇİR',
      'booking_confirmed': 'RANDEVU ONAYLANDI',
      'meds_vitals_reminders': 'İLAÇ & VİTAL HATIRLATICILAR',
      'new_reminder': 'YENİ HATIRLATICI',
      'edit_reminder': 'HATIRLATICI DÜZENLE',
      'patient_profile': 'HASTA PROFİLİ',
      'save_profile': 'PROFİLİ KAYDET',
      'connected_devices': 'Bağlı Cihazlar',
    },
    'العربية': {
      'drgodly': 'DRGODLY',
      'hi': 'أهلاً',
      'patient': 'المريض',
      'steps': 'الخطوات',
      'calories': 'السعرات',
      'active_time': 'وقت النشاط',
      'sleep': 'النوم',
      'general_app_config': 'إعدادات عامة',
      'app_language': 'لغة التطبيق',
      'start_week_on': 'بدء الأسبوع في',
      'select_language': 'اختر اللغة',
      'start_week_title': 'بدء الأسبوع في',
      'specialists_directory': 'دليل الأطباء',
      'select_date_time': 'اختر التاريخ والوقت',
      'review_booking': 'مراجعة الحجز',
      'booking_confirmed': 'تم تأكيد الحجز',
      'meds_vitals_reminders': 'تذكيرات الأدوية والمؤشرات',
      'new_reminder': 'تذكير جديد',
      'edit_reminder': 'تعديل التذكير',
      'patient_profile': 'ملف المريض',
      'save_profile': 'حفظ الملف',
      'connected_devices': 'الأجهزة المتصلة',
    },
    'Indonesia': {
      'drgodly': 'DRGODLY',
      'hi': 'HALO',
      'patient': 'PASIEN',
      'steps': 'LANGKAH',
      'calories': 'KALORI',
      'active_time': 'WAKTU AKTIF',
      'sleep': 'TIDUR',
      'general_app_config': 'PENGATURAN UMUM',
      'app_language': 'Bahasa Aplikasi',
      'start_week_on': 'Mulai minggu hari',
      'select_language': 'PILIH BAHASA',
      'start_week_title': 'MULAI MINGGU HARI',
      'specialists_directory': 'DIREKTORI SPESIALIS',
      'select_date_time': 'PILIH TANGGAL & WAKTU',
      'review_booking': 'TINJAU RESERVASI',
      'booking_confirmed': 'RESERVASI DIKONFIRMASI',
      'meds_vitals_reminders': 'PENGINGAT OBAT & VITAL',
      'new_reminder': 'PENGINGAT BARU',
      'edit_reminder': 'EDIT PENGINGAT',
      'patient_profile': 'PROFIL PASIEN',
      'save_profile': 'SIMPAN PROFIL',
      'connected_devices': 'Perangkat Terhubung',
    },
    '简体中文': {
      'drgodly': 'DRGODLY',
      'hi': '你好',
      'patient': '患者',
      'steps': '步数',
      'calories': '卡路里',
      'active_time': '活跃时间',
      'sleep': '睡眠时间',
      'general_app_config': '一般设置',
      'app_language': '应用语言',
      'start_week_on': '每周开始于',
      'select_language': '选择语言',
      'start_week_title': '每周开始于',
      'specialists_directory': '专家目录',
      'select_date_time': '选择日期与时间',
      'review_booking': '核对预约信息',
      'booking_confirmed': '预约成功',
      'meds_vitals_reminders': '服药与体征提醒',
      'new_reminder': '新增提醒',
      'edit_reminder': '编辑提醒',
      'patient_profile': '患者档案',
      'save_profile': '保存档案',
      'connected_devices': '已连接的设备',
    },
    '繁體中文': {
      'drgodly': 'DRGODLY',
      'hi': '你好',
      'patient': '患者',
      'steps': '步數',
      'calories': '卡路里',
      'active_time': '活躍時間',
      'sleep': '睡眠時間',
      'general_app_config': '一般設定',
      'app_language': '應用語言',
      'start_week_on': '每周開始於',
      'select_language': '選擇語言',
      'start_week_title': '每周開始於',
      'specialists_directory': '專家目錄',
      'select_date_time': '選擇日期與時間',
      'review_booking': '核對預約資訊',
      'booking_confirmed': '預約成功',
      'meds_vitals_reminders': '服藥與體徵提醒',
      'new_reminder': '新增提醒',
      'edit_reminder': '編輯提醒',
      'patient_profile': '患者檔案',
      'save_profile': '保存檔案',
      'connected_devices': '已連接的設備',
    },
    'فارسی': {
      'drgodly': 'DRGODLY',
      'hi': 'سلام',
      'patient': 'بیمار',
      'steps': 'گام‌ها',
      'calories': 'کالری',
      'active_time': 'زمان فعالیت',
      'sleep': 'خواب',
      'general_app_config': 'تنظیمات عمومی',
      'app_language': 'زبان برنامه',
      'start_week_on': 'شروع هفته از',
      'select_language': 'انتخاب زبان',
      'start_week_title': 'شروع هفته از',
      'specialists_directory': 'فهرست متخصصان',
      'select_date_time': 'انتخاب تاریخ و زمان',
      'review_booking': 'بررسی نوبت',
      'booking_confirmed': 'نوبت تایید شد',
      'meds_vitals_reminders': 'یادآورهای دارو و علائم',
      'new_reminder': 'یادآور جدید',
      'edit_reminder': 'ویرایش یادآور',
      'patient_profile': 'پروفایل بیمار',
      'save_profile': 'ذخیره پروفایل',
      'connected_devices': 'دستگاه‌های متصل',
    },
    'Tiếng Việt': {
      'drgodly': 'DRGODLY',
      'hi': 'XIN CHÀO',
      'patient': 'BỆNH NHÂN',
      'steps': 'BƯỚC CHÂN',
      'calories': 'CALO',
      'active_time': 'THỜI GIAN HOẠT ĐỘNG',
      'sleep': 'GIẤC NGỦ',
      'general_app_config': 'CẤU HÌNH CHUNG',
      'app_language': 'Ngôn ngữ ứng dụng',
      'start_week_on': 'Bắt đầu tuần vào',
      'select_language': 'CHỌN NGÔN NGỮ',
      'start_week_title': 'BẮT ĐẦU TUẦN VÀO',
      'specialists_directory': 'DANH SÁCH BÁC SĨ',
      'select_date_time': 'CHỌN NGÀY & GIỜ',
      'review_booking': 'KIỂM TRA LỊCH ĐẶT',
      'booking_confirmed': 'ĐÃ XÁC NHẬN ĐẶT LỊCH',
      'meds_vitals_reminders': 'NHẮC NHỞ THUỐC & CHỈ SỐ',
      'new_reminder': 'NHẮC NHỞ MỚI',
      'edit_reminder': 'SỬA NHẮC NHỞ',
      'patient_profile': 'HỒ SƠ BỆNH NHÂN',
      'save_profile': 'LƯU HỒ SƠ',
      'connected_devices': 'Thiết bị Kết nối',
    },
    'ไทย': {
      'drgodly': 'DRGODLY',
      'hi': 'สวัสดี',
      'patient': 'ผู้ป่วย',
      'steps': 'ก้าวเดิน',
      'calories': 'แคลอรี',
      'active_time': 'เวลาออกกำลังกาย',
      'sleep': 'นอนหลับ',
      'general_app_config': 'ตั้งค่าทั่วไป',
      'app_language': 'ภาษาของแอป',
      'start_week_on': 'เริ่มวันแรกของสัปดาห์',
      'select_language': 'เลือกภาษา',
      'start_week_title': 'เริ่มวันแรกของสัปดาห์',
      'specialists_directory': 'รายชื่อแพทย์ผู้เชี่ยวชาญ',
      'select_date_time': 'เลือกวันและเวลา',
      'review_booking': 'ตรวจสอบการจอง',
      'booking_confirmed': 'ยืนยันการจองเรียบร้อย',
      'meds_vitals_reminders': 'แจ้งเตือนทานยาและวัดสัญญาณชีพ',
      'new_reminder': 'เพิ่มการแจ้งเตือนใหม่',
      'edit_reminder': 'แก้ไขการแจ้งเตือน',
      'patient_profile': 'ประวัติผู้ป่วย',
      'save_profile': 'บันทึกประวัติ',
      'connected_devices': 'อุปกรณ์ที่เชื่อมต่อ',
    },
  };

  /// Translate a key dynamically based on current AppLanguage state
  static String translate(BuildContext context, String key, {String? defaultText}) {
    try {
      final language = Provider.of<SettingsViewModel>(context).appLanguage;
      final dict = _translations[language];
      if (dict != null && dict.containsKey(key)) {
        return dict[key]!;
      }
    } catch (_) {
      // Swallowed, fall through to default text
    }
    
    // Return default text if translation not found or settings not loaded
    if (defaultText != null) return defaultText;

    // Direct english dictionary fallback
    final engDict = _translations['English'];
    if (engDict != null && engDict.containsKey(key)) {
      return engDict[key]!;
    }
    return key;
  }
}
